<?php


//try {
//    $t = 0;
//    $i = 1 / $t;
//    throw new Exception('This is a test exception');
//}
//catch (Exception $e) {
//    echo 'Caught exception: ',  $e->getMessage(), "\n";
//}

//throw new Exception('This is a test exception');
phpinfo();


//echo "Hello, World!";
error_log("Hello2, errors!");